/**
 * Auto-generated by scripts/generate-tts.mjs — do not edit by hand.
 * Re-run the script to add new phrases.
 */
export const TTS_MANIFEST: Record<string, string> = {
  "session-intro--new-user": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/amelia/session-intro--new-user.mp3",
  "session-intro--returning": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/amelia/session-intro--returning.mp3",
  "session-intro--watch": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/amelia/session-intro--watch.mp3",
  "session-intro--your-turn": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/amelia/session-intro--your-turn.mp3",
  "session-intro--ready": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/amelia/session-intro--ready.mp3",
  "feedback--correct": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/alistair/feedback--correct.mp3",
  "feedback--try-again": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/alistair/feedback--try-again.mp3",
  "feedback--great-sentence": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/alistair/feedback--great-sentence.mp3",
  "feedback--check-order": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/alistair/feedback--check-order.mp3",
  "cap-step--intro": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/alistair/cap-step--intro.mp3",
  "cap-step--done": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/alistair/cap-step--done.mp3",
  "xp--earned": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/amelia/xp--earned.mp3",
  "xp--streak": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/amelia/xp--streak.mp3",
  "xp--level-up": "https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio/amelia/xp--level-up.mp3"
}
