/**
 * TTS Manifest — maps audio keys to ElevenLabs MP3 URLs in Supabase Storage.
 *
 * Two buckets:
 *   tts-audio  — legacy keys (cap-step--, session-intro--, xp--, level-intro--)
 *   pwp-audio  — all dot-notation keys (gamification.*, step.*, feedback.*, etc.)
 *
 * Voice assignment:
 *   Alistair (l30f87tf05uxyknGdDw6) — step instructions, level intros, guidance
 *   Amelia   (ZF6FPAbjXT4488VcRRnw) — feedback, celebration, gamification, onboarding
 *   Alice    (ZEt85AU1ui8Rr8FxNslW) — variety (cap-step prompts, some error feedback)
 *
 * Missing keys fall back to browser Web Speech API.
 * All 162 keys are fully generated and uploaded as of 2026-05-14.
 * To add new keys: add entries to pwp_audio_seed.sql, run generate-pwp-audio.mjs --upload,
 * then add the new URLs here using the PWPAUDIO constant.
 */

const PWPAUDIO = 'https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/pwp-audio'
const TTSAUDIO = 'https://gzmgjkbtsvezfclmreru.supabase.co/storage/v1/object/public/tts-audio'

export const TTS_MANIFEST: Record<string, string> = {

  // ── Legacy keys (tts-audio bucket) ──────────────────────────────────────────
  "session-intro--new-user":   `${TTSAUDIO}/amelia/session-intro--new-user.mp3`,
  "session-intro--returning":  `${TTSAUDIO}/amelia/session-intro--returning.mp3`,
  "session-intro--watch":      `${TTSAUDIO}/amelia/session-intro--watch.mp3`,
  "session-intro--your-turn":  `${TTSAUDIO}/amelia/session-intro--your-turn.mp3`,
  "session-intro--ready":      `${TTSAUDIO}/amelia/session-intro--ready.mp3`,
  "feedback--correct":         `${TTSAUDIO}/alistair/feedback--correct.mp3`,
  "feedback--try-again":       `${TTSAUDIO}/alistair/feedback--try-again.mp3`,
  "feedback--great-sentence":  `${TTSAUDIO}/alistair/feedback--great-sentence.mp3`,
  "feedback--check-order":     `${TTSAUDIO}/alistair/feedback--check-order.mp3`,
  "cap-step--intro":           `${TTSAUDIO}/alistair/cap-step--intro.mp3`,
  "cap-step--done":            `${TTSAUDIO}/alistair/cap-step--done.mp3`,
  "xp--earned":                `${TTSAUDIO}/amelia/xp--earned.mp3`,
  "xp--streak":                `${TTSAUDIO}/amelia/xp--streak.mp3`,
  "xp--level-up":              `${TTSAUDIO}/amelia/xp--level-up.mp3`,
  "level-intro--1":  `${TTSAUDIO}/alistair/level-intro--1.mp3`,
  "level-intro--2":  `${TTSAUDIO}/amelia/level-intro--2.mp3`,
  "level-intro--3":  `${TTSAUDIO}/alistair/level-intro--3.mp3`,
  "level-intro--4":  `${TTSAUDIO}/amelia/level-intro--4.mp3`,
  "level-intro--5":  `${TTSAUDIO}/alistair/level-intro--5.mp3`,
  "level-intro--6":  `${TTSAUDIO}/amelia/level-intro--6.mp3`,
  "level-intro--7":  `${TTSAUDIO}/alistair/level-intro--7.mp3`,
  "level-intro--8":  `${TTSAUDIO}/amelia/level-intro--8.mp3`,
  "level-intro--9":  `${TTSAUDIO}/alistair/level-intro--9.mp3`,
  "level-intro--10": `${TTSAUDIO}/amelia/level-intro--10.mp3`,
  "level-intro--11": `${TTSAUDIO}/alistair/level-intro--11.mp3`,
  "level-intro--12": `${TTSAUDIO}/amelia/level-intro--12.mp3`,
  "level-intro--13": `${TTSAUDIO}/alistair/level-intro--13.mp3`,
  "level-intro--14": `${TTSAUDIO}/amelia/level-intro--14.mp3`,
  "level-intro--15": `${TTSAUDIO}/alistair/level-intro--15.mp3`,
  "level-intro--16": `${TTSAUDIO}/amelia/level-intro--16.mp3`,
  "level-intro--17": `${TTSAUDIO}/alistair/level-intro--17.mp3`,
  "level-intro--18": `${TTSAUDIO}/amelia/level-intro--18.mp3`,
  "level-intro--19": `${TTSAUDIO}/alistair/level-intro--19.mp3`,
  "level-intro--20": `${TTSAUDIO}/amelia/level-intro--20.mp3`,
  "level-intro--21": `${TTSAUDIO}/alistair/level-intro--21.mp3`,
  "level-intro--22": `${TTSAUDIO}/amelia/level-intro--22.mp3`,
  "level-intro--23": `${TTSAUDIO}/alistair/level-intro--23.mp3`,
  "level-intro--24": `${TTSAUDIO}/amelia/level-intro--24.mp3`,
  "level-intro--25": `${TTSAUDIO}/alistair/level-intro--25.mp3`,
  "level-intro--26": `${TTSAUDIO}/amelia/level-intro--26.mp3`,
  "level-intro--27": `${TTSAUDIO}/alistair/level-intro--27.mp3`,
  "level-intro--28": `${TTSAUDIO}/amelia/level-intro--28.mp3`,
  "level-intro--29": `${TTSAUDIO}/alistair/level-intro--29.mp3`,
  "level-intro--30": `${TTSAUDIO}/amelia/level-intro--30.mp3`,
  "level-intro--31": `${TTSAUDIO}/alistair/level-intro--31.mp3`,
  "level-intro--32": `${TTSAUDIO}/amelia/level-intro--32.mp3`,
  "level-intro--33": `${TTSAUDIO}/alistair/level-intro--33.mp3`,
  "level-intro--34": `${TTSAUDIO}/amelia/level-intro--34.mp3`,
  "level-intro--35": `${TTSAUDIO}/alistair/level-intro--35.mp3`,
  "level-intro--36": `${TTSAUDIO}/alistair/level-intro--36.mp3`,
  "level-intro--37": `${TTSAUDIO}/alistair/level-intro--37.mp3`,
  "level-intro--38": `${TTSAUDIO}/alistair/level-intro--38.mp3`,
  "level-intro--39": `${TTSAUDIO}/alistair/level-intro--39.mp3`,
  "level-intro--40": `${TTSAUDIO}/alistair/level-intro--40.mp3`,
  "level-intro--41": `${TTSAUDIO}/alistair/level-intro--41.mp3`,
  "level-intro--42": `${TTSAUDIO}/alistair/level-intro--42.mp3`,
  "level-intro--43": `${TTSAUDIO}/alistair/level-intro--43.mp3`,
  "level-intro--44": `${TTSAUDIO}/alistair/level-intro--44.mp3`,
  "level-intro--45": `${TTSAUDIO}/alistair/level-intro--45.mp3`,
  "level-intro--46": `${TTSAUDIO}/alistair/level-intro--46.mp3`,
  "level-intro--47": `${TTSAUDIO}/alistair/level-intro--47.mp3`,
  "level-intro--48": `${TTSAUDIO}/alistair/level-intro--48.mp3`,
  "level-intro--49": `${TTSAUDIO}/alistair/level-intro--49.mp3`,
  "level-intro--50": `${TTSAUDIO}/alistair/level-intro--50.mp3`,
  "level-intro--51": `${TTSAUDIO}/alistair/level-intro--51.mp3`,
  "level-intro--52": `${TTSAUDIO}/alistair/level-intro--52.mp3`,
  "level-intro--53": `${TTSAUDIO}/alistair/level-intro--53.mp3`,
  "level-intro--54": `${TTSAUDIO}/alistair/level-intro--54.mp3`,
  "level-intro--55": `${TTSAUDIO}/alistair/level-intro--55.mp3`,
  "level-intro--56": `${TTSAUDIO}/alistair/level-intro--56.mp3`,
  "level-intro--57": `${TTSAUDIO}/alistair/level-intro--57.mp3`,
  "level-intro--58": `${TTSAUDIO}/alistair/level-intro--58.mp3`,
  "level-intro--59": `${TTSAUDIO}/alistair/level-intro--59.mp3`,
  "level-intro--60": `${TTSAUDIO}/alistair/level-intro--60.mp3`,
  "level-intro--61": `${TTSAUDIO}/alistair/level-intro--61.mp3`,
  "level-intro--62": `${TTSAUDIO}/alistair/level-intro--62.mp3`,
  "level-intro--63": `${TTSAUDIO}/alistair/level-intro--63.mp3`,
  "level-intro--64": `${TTSAUDIO}/alistair/level-intro--64.mp3`,
  "level-intro--65": `${TTSAUDIO}/alistair/level-intro--65.mp3`,
  "level-intro--66": `${TTSAUDIO}/alistair/level-intro--66.mp3`,
  "level-intro--67": `${TTSAUDIO}/alistair/level-intro--67.mp3`,

  // ── Celebration (Amelia — pwp-audio bucket) ──────────────────────────────────
  "celebration.badge_builder":          `${PWPAUDIO}/amelia/celebrations/amelia_celebration_badge-builder.mp3`,
  "celebration.badge_composer":         `${PWPAUDIO}/amelia/celebrations/amelia_celebration_badge-composer.mp3`,
  "celebration.badge_foundation":       `${PWPAUDIO}/amelia/celebrations/amelia_celebration_badge-foundation.mp3`,
  "celebration.badge_master":           `${PWPAUDIO}/amelia/celebrations/amelia_celebration_badge-master.mp3`,
  "celebration.badge_paragraph":        `${PWPAUDIO}/amelia/celebrations/amelia_celebration_badge-paragraph.mp3`,
  "celebration.chapter_complete":       `${PWPAUDIO}/amelia/celebrations/amelia_celebration_chapter-complete.mp3`,
  "celebration.level_complete":         `${PWPAUDIO}/amelia/celebrations/amelia_celebration_level-complete.mp3`,
  "celebration.paragraph_phase_unlock": `${PWPAUDIO}/amelia/celebrations/amelia_celebration_paragraph-phase-unlock.mp3`,
  "celebration.programme_complete":     `${PWPAUDIO}/amelia/celebrations/amelia_celebration_programme-complete.mp3`,
  "celebration.quiz_checkpoint":        `${PWPAUDIO}/amelia/celebrations/amelia_celebration_quiz-checkpoint.mp3`,
  "celebration.streak_30":              `${PWPAUDIO}/amelia/celebrations/amelia_celebration_streak-30.mp3`,
  "celebration.streak_7":               `${PWPAUDIO}/amelia/celebrations/amelia_celebration_streak-7.mp3`,

  // ── Feedback — correct variants (Amelia) ─────────────────────────────────────
  "feedback.correct_v1":  `${PWPAUDIO}/amelia/feedback/amelia_feedback_correct-v1.mp3`,
  "feedback.correct_v2":  `${PWPAUDIO}/amelia/feedback/amelia_feedback_correct-v2.mp3`,
  "feedback.correct_v3":  `${PWPAUDIO}/amelia/feedback/amelia_feedback_correct-v3.mp3`,
  "feedback.correct_v4":  `${PWPAUDIO}/amelia/feedback/amelia_feedback_correct-v4.mp3`,
  "feedback.correct_v5":  `${PWPAUDIO}/amelia/feedback/amelia_feedback_correct-v5.mp3`,
  "feedback.correct_v6":  `${PWPAUDIO}/amelia/feedback/amelia_feedback_correct-v6.mp3`,
  "feedback.correct_v7":  `${PWPAUDIO}/amelia/feedback/amelia_feedback_correct-v7.mp3`,
  "feedback.correct_v8":  `${PWPAUDIO}/amelia/feedback/amelia_feedback_correct-v8.mp3`,
  "feedback.correct_v9":  `${PWPAUDIO}/amelia/feedback/amelia_feedback_correct-v9.mp3`,
  "feedback.correct_v10": `${PWPAUDIO}/amelia/feedback/amelia_feedback_correct-v10.mp3`,
  "feedback.correct_v11": `${PWPAUDIO}/amelia/feedback/amelia_feedback_correct-v11.mp3`,
  "feedback.correct_v12": `${PWPAUDIO}/amelia/feedback/amelia_feedback_correct-v12.mp3`,

  // ── Feedback — retry correct (Amelia) ────────────────────────────────────────
  "feedback.retry_correct_v1": `${PWPAUDIO}/amelia/feedback/amelia_feedback_retry-correct-v1.mp3`,
  "feedback.retry_correct_v2": `${PWPAUDIO}/amelia/feedback/amelia_feedback_retry-correct-v2.mp3`,
  "feedback.retry_correct_v3": `${PWPAUDIO}/amelia/feedback/amelia_feedback_retry-correct-v3.mp3`,
  "feedback.retry_correct_v4": `${PWPAUDIO}/amelia/feedback/amelia_feedback_retry-correct-v4.mp3`,
  "feedback.retry_correct_v5": `${PWPAUDIO}/amelia/feedback/amelia_feedback_retry-correct-v5.mp3`,
  "feedback.retry_correct_v6": `${PWPAUDIO}/amelia/feedback/amelia_feedback_retry-correct-v6.mp3`,
  "feedback.retry_correct_v7": `${PWPAUDIO}/amelia/feedback/amelia_feedback_retry-correct-v7.mp3`,
  "feedback.retry_correct_v8": `${PWPAUDIO}/amelia/feedback/amelia_feedback_retry-correct-v8.mp3`,

  // ── Feedback — errors (Amelia, uploaded) ─────────────────────────────────────
  "feedback.error_general":              `${PWPAUDIO}/amelia/feedback/amelia_feedback_error-general.mp3`,
  "feedback.error_missing_adjective":    `${PWPAUDIO}/amelia/feedback/amelia_feedback_error-missing-adjective.mp3`,
  "feedback.error_missing_adverb":       `${PWPAUDIO}/amelia/feedback/amelia_feedback_error-missing-adverb.mp3`,
  "feedback.error_missing_comma":        `${PWPAUDIO}/amelia/feedback/amelia_feedback_error-missing-comma.mp3`,
  "feedback.error_missing_conjunction":  `${PWPAUDIO}/amelia/feedback/amelia_feedback_error-missing-conjunction.mp3`,
  "feedback.error_missing_determiner":   `${PWPAUDIO}/amelia/feedback/amelia_feedback_error-missing-determiner.mp3`,
  "feedback.error_missing_object":       `${PWPAUDIO}/amelia/feedback/amelia_feedback_error-missing-object.mp3`,
  "feedback.error_missing_preposition":  `${PWPAUDIO}/amelia/feedback/amelia_feedback_error-missing-preposition.mp3`,
  "feedback.error_wrong_pronoun":        `${PWPAUDIO}/amelia/feedback/amelia_feedback_error-wrong-pronoun.mp3`,
  "feedback.error_wrong_tense":          `${PWPAUDIO}/amelia/feedback/amelia_feedback_error-wrong-tense.mp3`,
  "feedback.error_wrong_order":          `${PWPAUDIO}/amelia/feedback/amelia_feedback_error-wrong-order.mp3`,
  "feedback.error_wrong_subject_type":   `${PWPAUDIO}/alice/feedback/alice_feedback_error-wrong-subject-type.mp3`,
  "feedback.error_extra_element":        `${PWPAUDIO}/amelia/feedback/amelia_feedback_error-extra-element.mp3`,
  "feedback.error_incomplete":           `${PWPAUDIO}/amelia/feedback/amelia_feedback_error-incomplete.mp3`,

  // ── Gamification (Amelia) ─────────────────────────────────────────────────────
  "gamification.first_correct":   `${PWPAUDIO}/amelia/gamification/amelia_gamification_first-correct.mp3`,
  "gamification.halfway":         `${PWPAUDIO}/amelia/gamification/amelia_gamification_halfway.mp3`,
  "gamification.lives_lost_one":  `${PWPAUDIO}/amelia/gamification/amelia_gamification_lives-lost-one.mp3`,
  "gamification.lives_zero":      `${PWPAUDIO}/amelia/gamification/amelia_gamification_lives-zero.mp3`,
  "gamification.streak_broken":   `${PWPAUDIO}/amelia/gamification/amelia_gamification_streak-broken.mp3`,
  "gamification.streak_continue": `${PWPAUDIO}/amelia/gamification/amelia_gamification_streak-continue.mp3`,
  "gamification.xp_10":           `${PWPAUDIO}/amelia/gamification/amelia_gamification_xp-10.mp3`,
  "gamification.xp_25_bonus":     `${PWPAUDIO}/amelia/gamification/amelia_gamification_xp-25-bonus.mp3`,
  "gamification.xp_5":            `${PWPAUDIO}/amelia/gamification/amelia_gamification_xp-5.mp3`,
  "gamification.xp_50_bonus":     `${PWPAUDIO}/amelia/gamification/amelia_gamification_xp-50-bonus.mp3`,

  // ── Guidance (Alistair) ───────────────────────────────────────────────────────
  "guidance.explain_adjective":           `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-adjective.mp3`,
  "guidance.explain_adverb_manner":       `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-adverb-manner.mp3`,
  "guidance.explain_adverb_place":        `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-adverb-place.mp3`,
  "guidance.explain_adverb_time":         `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-adverb-time.mp3`,
  "guidance.explain_conjunction_coord":   `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-conjunction-coord.mp3`,
  "guidance.explain_conjunction_sub":     `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-conjunction-sub.mp3`,
  "guidance.explain_determiner":          `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-determiner.mp3`,
  "guidance.explain_fronted_adverbial":   `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-fronted-adverbial.mp3`,
  "guidance.explain_noun":                `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-noun.mp3`,
  "guidance.explain_noun_phrase":         `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-noun-phrase.mp3`,
  "guidance.explain_preposition":         `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-preposition.mp3`,
  "guidance.explain_pronoun":             `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-pronoun.mp3`,
  "guidance.explain_relative_clause":     `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-relative-clause.mp3`,
  "guidance.explain_rule":                `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-rule.mp3`,
  "guidance.explain_transition":          `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-transition.mp3`,
  "guidance.explain_verb":                `${PWPAUDIO}/alistair/guidance/alistair_guidance_explain-verb.mp3`,
  "guidance.model_sentence":              `${PWPAUDIO}/alistair/guidance/alistair_guidance_model-sentence.mp3`,
  "guidance.remind_formula":              `${PWPAUDIO}/alistair/guidance/alistair_guidance_remind-formula.mp3`,
  "guidance.adaptive_open": `${PWPAUDIO}/alistair/guidance/alistair_guidance_adaptive-open.mp3`,

  // ── Level start intros (Alistair) ─────────────────────────────────────────────
  "level_start.level_01": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-01.mp3`,
  "level_start.level_02": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-02.mp3`,
  "level_start.level_03": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-03.mp3`,
  "level_start.level_04": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-04.mp3`,
  "level_start.level_05": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-05.mp3`,
  "level_start.level_06": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-06.mp3`,
  "level_start.level_07": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-07.mp3`,
  "level_start.level_08": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-08.mp3`,
  "level_start.level_09": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-09.mp3`,
  "level_start.level_10": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-10.mp3`,
  "level_start.level_11": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-11.mp3`,
  "level_start.level_12": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-12.mp3`,
  "level_start.level_13": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-13.mp3`,
  "level_start.level_14": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-14.mp3`,
  "level_start.level_15": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-15.mp3`,
  "level_start.level_16": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-16.mp3`,
  "level_start.level_17": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-17.mp3`,
  "level_start.level_18": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-18.mp3`,
  "level_start.level_19": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-19.mp3`,
  "level_start.level_20": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-20.mp3`,
  "level_start.level_21": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-21.mp3`,
  "level_start.level_22": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-22.mp3`,
  "level_start.level_23": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-23.mp3`,
  "level_start.level_24": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-24.mp3`,
  "level_start.level_25": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-25.mp3`,
  "level_start.level_26": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-26.mp3`,
  "level_start.level_27": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-27.mp3`,
  "level_start.level_28": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-28.mp3`,
  "level_start.level_29": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-29.mp3`,
  "level_start.level_30": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-30.mp3`,
  "level_start.level_31": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-31.mp3`,
  "level_start.level_32": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-32.mp3`,
  "level_start.level_33": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-33.mp3`,
  "level_start.level_34": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-34.mp3`,
  "level_start.level_35": `${PWPAUDIO}/alistair/level-start/alistair_level-start_level-35.mp3`,

  // ── Onboarding (Amelia) ───────────────────────────────────────────────────────
  "onboarding.first_login":     `${PWPAUDIO}/amelia/onboarding/amelia_onboarding_first-login.mp3`,
  "onboarding.returning_user":  `${PWPAUDIO}/amelia/onboarding/amelia_onboarding_returning-user.mp3`,
  "onboarding.what_is_chain":   `${PWPAUDIO}/amelia/onboarding/amelia_onboarding_what-is-chain.mp3`,
  "onboarding.what_is_formula": `${PWPAUDIO}/amelia/onboarding/amelia_onboarding_what-is-formula.mp3`,
  "onboarding.xp_explained":    `${PWPAUDIO}/amelia/onboarding/amelia_onboarding_xp-explained.mp3`,

  // ── Quiz (Alistair intro, Amelia pass/fail) ───────────────────────────────────
  "quiz.all_prompts_visible": `${PWPAUDIO}/alistair/quiz/alistair_quiz_all-prompts-visible.mp3`,
  "quiz.check_formula":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_check-formula.mp3`,
  "quiz.check_tense":         `${PWPAUDIO}/alistair/quiz/alistair_quiz_check-tense.mp3`,
  "quiz.here_is_prompt":      `${PWPAUDIO}/alistair/quiz/alistair_quiz_here-is-prompt.mp3`,
  "quiz.fail_v1":             `${PWPAUDIO}/amelia/quiz/amelia_quiz_fail-v1.mp3`,
  "quiz.fail_v2":             `${PWPAUDIO}/amelia/quiz/amelia_quiz_fail-v2.mp3`,
  "quiz.fail_v3":             `${PWPAUDIO}/amelia/quiz/amelia_quiz_fail-v3.mp3`,
  "quiz.pass_v1":             `${PWPAUDIO}/amelia/quiz/amelia_quiz_pass-v1.mp3`,
  "quiz.pass_v2":             `${PWPAUDIO}/amelia/quiz/amelia_quiz_pass-v2.mp3`,
  "quiz.pass_v3":             `${PWPAUDIO}/amelia/quiz/amelia_quiz_pass-v3.mp3`,
  "quiz.pass_v4":             `${PWPAUDIO}/amelia/quiz/amelia_quiz_pass-v4.mp3`,
  "quiz.pass_v5":             `${PWPAUDIO}/amelia/quiz/amelia_quiz_pass-v5.mp3`,
  "quiz.start_quiz_01":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_start-quiz-01.mp3`,
  "quiz.start_quiz_02":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_start-quiz-02.mp3`,
  "quiz.start_quiz_03":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_start-quiz-03.mp3`,
  "quiz.start_quiz_04":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_start-quiz-04.mp3`,
  "quiz.start_quiz_05":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_start-quiz-05.mp3`,
  "quiz.start_quiz_06":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_start-quiz-06.mp3`,
  "quiz.start_quiz_07":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_start-quiz-07.mp3`,
  "quiz.start_quiz_08":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_start-quiz-08.mp3`,
  "quiz.start_quiz_09":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_start-quiz-09.mp3`,
  "quiz.start_quiz_10":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_start-quiz-10.mp3`,
  "quiz.start_quiz_11":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_start-quiz-11.mp3`,
  "quiz.start_quiz_12":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_start-quiz-12.mp3`,
  "quiz.start_quiz_13":       `${PWPAUDIO}/alistair/quiz/alistair_quiz_start-quiz-13.mp3`,

  // ── Step instructions (Alistair) ──────────────────────────────────────────────
  "step.applied_prepwp":    `${PWPAUDIO}/alistair/step-instructions/alistair_step_applied-prepwp.mp3`,
  "step.command_no_subject":`${PWPAUDIO}/alistair/step-instructions/alistair_step_command-no-subject.mp3`,
  "step.consolidation_intro":`${PWPAUDIO}/alistair/step-instructions/alistair_step_consolidation-intro.mp3`,
  "step.example_prompt":    `${PWPAUDIO}/alistair/step-instructions/alistair_step_example-prompt.mp3`,
  "step.formula_intro":     `${PWPAUDIO}/alistair/step-instructions/alistair_step_formula-intro.mp3`,
  "step.fronted_comma":     `${PWPAUDIO}/alistair/step-instructions/alistair_step_fronted-comma.mp3`,
  "step.gap_slot_intro":    `${PWPAUDIO}/alistair/step-instructions/alistair_step_gap-slot-intro.mp3`,
  "step.new_element_intro": `${PWPAUDIO}/alistair/step-instructions/alistair_step_new-element-intro.mp3`,
  "step.paragraph_close":   `${PWPAUDIO}/alistair/step-instructions/alistair_step_paragraph-close.mp3`,
  "step.paragraph_lead":    `${PWPAUDIO}/alistair/step-instructions/alistair_step_paragraph-lead.mp3`,
  "step.paragraph_support": `${PWPAUDIO}/alistair/step-instructions/alistair_step_paragraph-support.mp3`,
  "step.question_flip":     `${PWPAUDIO}/alistair/step-instructions/alistair_step_question-flip.mp3`,
  "step.subject_chip":      `${PWPAUDIO}/alistair/step-instructions/alistair_step_subject-chip.mp3`,
  "step.tense_variety":     `${PWPAUDIO}/alistair/step-instructions/alistair_step_tense-variety.mp3`,
  "step.three_stage":       `${PWPAUDIO}/alistair/step-instructions/alistair_step_three-stage.mp3`,
  "step.transition_arrow":  `${PWPAUDIO}/alistair/step-instructions/alistair_step_transition-arrow.mp3`,
  "step.word_bank_intro":   `${PWPAUDIO}/alistair/step-instructions/alistair_step_word-bank-intro.mp3`,
  "step.write_now":         `${PWPAUDIO}/alistair/step-instructions/alistair_step_write-now.mp3`,

  // ── Cap-step / Punctuation mechanic (Alice — variety) ────────────────────────
  "cap-step.capitalise":           `${PWPAUDIO}/alice/cap-step/alice_cap-step_capitalise.mp3`,
  "cap-step.punctuate":            `${PWPAUDIO}/alice/cap-step/alice_cap-step_punctuate.mp3`,
  "punctuation.capitalise_prompt": `${PWPAUDIO}/amelia/feedback/amelia_feedback_capitalise-prompt.mp3`,
  "punctuation.end_prompt":        `${PWPAUDIO}/alice/feedback/alice_feedback_end-prompt.mp3`,
}
